export interface IWorker {
  image: string | null;
  branchName: string;
  nationalityName: string;
  jobName: string;
  id: string;
  createdById: string | null;
  createdByName: string | null;
  age: number;
  name: string;
  dateOfExit: Date;
  phone: string;
  yearsOfExperience: number;
  residenceNumber: string;
  nationalityId: string;
  jobId: string;
  branchId: string;
  dateOfBirth: Date;
  operatingFees: number;
  religionId: number;
  religion: string;
  genderId: number;
  gender: string;
  languageId: number;
  language: string;
  firstEntryDate: Date;
  lastEntryDate: Date;
  visaExpiryDate: Date;
  workStartDate: Date;
  salary: number;
  passportNumber: string;
  borderNumber: string;
  lastEntryPort: string;
  visaType: string;
  externalOffice: string;
  skills: string;
  serviceProvided: string;
  workerTypeOfServicesIds: string[];
  workerTypeOfServices: string;
  jobStatus: string;
  jobStatusId: number;
  isActive: boolean;
}

// "image": null;
// "branchName": "noha";
// "nationalityName": "مصري2";
// "jobName": "noha";
// "id": "c2186056-880f-41c9-b83d-7b138fdd1bae";
// "createdById": null;
// "createdByName": null;
// "age": 2023;
// "name": "noha emad said";
// "dateOfExit": null;
// "phone": "01119577144";
// "yearsOfExperience": 2;
// "residenceNumber": "2323211";
// "nationalityId": "93d5aba3-c01d-43d4-89d6-88164fed9930";
// "jobId": "1cd1bc3d-07eb-4af3-b613-e36b65043226";
// "branchId": "2e431fb9-a75e-4815-9ebc-04684759a338";
// "dateOfBirth": "0001-01-01T00:00:00";
// "operatingFees": 20;
// "religionId": 0;
// "religion": "مسلم";
// "genderId": 0;
// "gender": "ذكر";
// "languageId": 12;
// "language": "الأردية";
// "firstEntryDate": "0001-01-01T00:00:00";
// "lastEntryDate": "0001-01-01T00:00:00";
// "visaExpiryDate": "0001-01-01T00:00:00";
// "workStartDate": "0001-01-01T00:00:00";
// "salary": 20;
// "passportNumber": "20";
// "borderNumber": "20";
// "lastEntryPort": "القاهره";
// "visaType": "مفتوح";
// "externalOffice": "القاهره";
// "skills": "front end developer";
// "serviceProvided": "60527dad-c917-44ba-8364-61bd5c0ebb65";
// "jobStatus": "تم الاستلام";
// "jobStatusId": 0;
// "isActive": false
